package com.unionpay.mobile.android.model;

import com.unionpay.mobile.android.views.order.l;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONObject;

/* loaded from: classes.dex */
public final class b {
    public static boolean aV = false;
    public static List<d> aW = null;
    public static boolean av = false;
    public static boolean aw = false;
    public static boolean bf = false;
    public static boolean bg = false;
    public static boolean bh = false;
    public static boolean bi = false;
    public com.unionpay.mobile.android.plugin.c D;
    public String be;
    public List<c> l;
    public String a = "1.9";
    public String b = null;
    public boolean c = false;
    public String d = null;
    public JSONArray e = null;
    public JSONObject f = null;
    public JSONObject g = null;
    public String h = null;
    public String i = null;
    public String j = "";
    public HashMap<String, String> k = null;
    public String m = null;
    public String n = null;
    public JSONArray o = null;
    public String p = null;
    public JSONObject q = null;
    public JSONObject r = null;
    public JSONObject s = null;
    public String t = null;

    /* renamed from: u, reason: collision with root package name */
    public JSONArray f39u = null;
    public String v = "";
    public String w = "";
    public JSONObject x = null;
    public JSONArray y = null;
    public String z = "";
    public boolean A = false;
    public JSONObject B = null;
    public JSONArray C = null;
    public boolean E = false;
    public boolean F = false;
    public boolean G = false;
    public String H = "0";
    public int I = 0;
    public String J = "";
    public String K = null;
    public String L = null;
    public String M = "";
    public String N = "";
    public JSONArray O = null;
    public boolean P = false;
    public String Q = null;
    public String R = null;
    public JSONArray S = null;
    public JSONObject T = null;
    public JSONObject U = null;
    public JSONObject V = null;
    public List<c> W = null;
    public JSONArray X = null;
    public JSONArray Y = null;
    public String Z = null;
    public String aa = "";
    public String ab = "";
    public int ac = 0;
    public String ad = "";
    public String ae = "";
    public String af = "";
    public JSONObject ag = null;
    public JSONObject ah = null;
    public String ai = null;
    public int aj = 0;
    public String ak = "";
    public String al = null;
    public String am = null;
    public String an = null;
    public String ao = null;
    public JSONObject ap = null;
    public JSONObject aq = null;
    public boolean ar = false;
    public boolean as = false;
    public boolean at = false;
    public boolean au = false;
    public boolean ax = false;
    public boolean ay = false;
    public boolean az = false;
    public JSONObject aA = null;
    public String aB = null;
    public String aC = null;
    public String aD = null;
    public String aE = null;
    public String aF = null;
    public String aG = null;
    public boolean aH = false;
    public int aI = 0;
    public int aJ = 0;
    public int aK = l.a.intValue();
    public int aL = l.b.intValue();
    public String aM = null;
    public String aN = null;
    public String aO = null;
    public JSONObject aP = null;
    public boolean aQ = false;
    public String aR = null;
    public String aS = null;
    public String aT = null;
    public boolean aU = false;
    public int aX = 0;
    public int aY = 0;
    public String aZ = null;
    public String ba = null;
    public String bb = null;
    public String bc = null;
    public String bd = null;
    public String bj = null;
    public String bk = null;
    public boolean bl = false;
    public c bm = null;
    public String bn = "";

    public b() {
        this.l = null;
        this.D = null;
        this.be = "";
        this.D = new com.unionpay.mobile.android.plugin.c();
        this.l = new ArrayList(1);
        aW = new ArrayList(1);
        bg = false;
        bh = false;
        bi = false;
        av = false;
        aw = false;
        this.be = "";
    }

    public final String a() {
        com.unionpay.mobile.android.plugin.c cVar = this.D;
        return (cVar == null || !(cVar.a == 2 || this.D.a == 3)) ? "1" : "2";
    }
}
